### ISSUE TITLE
[Question] ValueError: * must be a valid directory

### ISSUE THREAD

**Issue by Kristinita** [gerardroche/sublime-sesame#5]
### 1. Summary

I can not set path to my projects.

### 2. Settings

+ I have Sublime Text 3 Portable for Windows.
+ Absolute path to my Sublime Text working directory — `D:\Sublime Text 3 x64`
+ Absolute path to my `sublime-project` and `sublime-workspace` files — `D:\Sublime Text 3 x64\Data\Packages\User\Projects`.
+ I set user environment variable and restart Windows: `PROJECTS_PATH = D:\Sublime Text 3 x64\Data\Packages\User\Projects`
+ Example part of my `User/Preferences.sublime-settings`

```json
"open-sesame.projects_path": "PROJECTS_PATH",
"open-sesame.projects_depth": 1,
```

### 3. Steps to reproduce

I reproduce the problem in a version of Sublime Text without plugins and user settings.

I install Open Sesame → I restart Sublime Text → I open any file in Sublime Text → <kbd>Ctrl+Shift+P</kbd> (<kbd>⌘⇧p</kbd> for Mac) → `Open Sesame: Add Project Folder`.

### 4. Expected behavior

Successful add a project to the active window.

### 5. Actual behavior

```python
command: open_sesame_add_folder
Traceback (most recent call last):
  File "D:\Sublime Text 3 x64\sublime_plugin.py", line 797, in run_
    return self.run()
  File "plugin in D:\Sublime Text 3 x64\Data\Installed Packages\open-sesame.sublime-package", line 45, in run
  File "plugin in D:\Sublime Text 3 x64\Data\Installed Packages\open-sesame.sublime-package", line 78, in find_folders
ValueError: PROJECTS_PATH must be a valid directory
```

If

```json
"open-sesame.projects_path": "./Projects",
```

I get similar stack trace:

```python
command: open_sesame_add_folder
Traceback (most recent call last):
  File "D:\Sublime Text 3 x64\sublime_plugin.py", line 797, in run_
    return self.run()
  File "plugin in D:\Sublime Text 3 x64\Data\Installed Packages\open-sesame.sublime-package", line 45, in run
  File "plugin in D:\Sublime Text 3 x64\Data\Installed Packages\open-sesame.sublime-package", line 78, in find_folders
ValueError: ./Projects must be a valid directory
```

I try set path to my `Projects` directory use Sublime Text [**Build System variables**](http://docs.sublimetext.info/en/latest/reference/build_systems/configuration.html#build-system-variables) → I get similar behavior.

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126
**Package:**
I use the latest stable version of this package for Sublime Text 3

Thanks.

**Comment by gerardroche** [comment]
Thank you for a detailed report.

There are a few issues.

`PROJECTS_PATH` is not a environment variable, it's a string. So `"open-sesame.projects_path": "PROJECTS_PATH"` just sets the projects_path to a string `PROJECTS_PATH`. Assuming the environment variable is set correctly then changing it to ``"open-sesame.projects_path": "$PROJECTS_PATH"` will solve the issue it.

However, if you're setting the environment variable then you don't have to set the projects path in Sublime Text, this is one of the main advantages of using the environment variable. So given that you've set the PROJECTS_PATH environment, Open Sesame will auto detect and use it as the projects path. So you won't need to set `"open-sesame.projects_path": "$PROJECTS_PATH"`. 

`"open-sesame.projects_path": "./Projects"` won't work because `./` is the current working directory and you're probably not launching Sublime from that directory.

If the above fixes above don't solve the issue then try setting the absolute path.

    open-sesame.projects_path": "D:\Sublime Text 3 x64\Data\Packages\User\Projects"

The above should certainly work.

If the environment variable is set correctly i.e. `PROJECTS_PATH="D:\Sublime Text 3 x64\Data\Packages\User\Projects"` then the following should also work.

    open-sesame.projects_path": "$PROJECTS_PATH"

But of course if the above works then you don't even need to set it so remove the above setting and it should work too.

**Comment by Kristinita** [comment]
## Update

### 1. Settings

I set absolute path to my `Projects` folder in `User/Preferences.sublime-settings`:

```json
"open-sesame.keymaps": true,
"open-sesame.projects_depth": 2,
"open-sesame.projects_path": "D:\\Sublime Text 3 x64\\Data\\Packages\\User\\Projects",
```

### 2. Steps to reproduce

I restart Sublime Text after change settings → I open any file in Sublime Text →

1. <kbd>Ctrl+Shift+P</kbd> (<kbd>⌘⇧p</kbd> for Mac) → `Open Sesame: Open Project`.
1. <kbd>Ctrl+Shift+P</kbd> (<kbd>⌘⇧p</kbd> for Mac) → `Open Sesame: Add Project Folder.`

### 3. Expected behavior

Any actions.

### 4. Actual behavior

Nothing occurs. Also, I don't get output in Sublime Text console.

```python
command: open_sesame
command: open_sesame_add_folder
```

Thanks.

**Comment by gerardroche** [comment]
When you set `open-sesame.projects_path"` back to an invalid string

    "open-sesame.projects_path": "foobar",

does it still produce the exception: `ValueError: ./Projects must be a valid directory`?

I pushed a new release which will show a status message in the status bar if no projects can be found.

**Comment by markusgritsch** [comment]
When sesame.path contains one non-existent directory, the other valid paths are ignored altogether.

It would be nice if Sesame would be more tolerant and still process the remaining valid paths, like FuzzyFileNav does.

I use the same .sublime-settings file on two computers, where not every machine has the same folders.
